spring:
  application:
    name: CheckOn

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

